-- Eliminar tablas si existen
DROP TABLE IF EXISTS TRANSACTION;
DROP TABLE IF EXISTS CARD;
DROP TABLE IF EXISTS CUSTOMER;

-- Crear tabla CUSTOMER
CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) 
);

-- Insertar 2 clientes en la tabla CUSTOMER
INSERT INTO CUSTOMER (NAME, LAST_NAME, EMAIL) VALUES ('Juan', 'Pérez', 'juan.perez@example.com');
INSERT INTO CUSTOMER (NAME, LAST_NAME, EMAIL) VALUES ('Ana', 'Gómez', 'ana.gomez@example.com');


-- Crear tabla CARD con relación a CUSTOMER
CREATE TABLE IF NOT EXISTS CARD (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT,
    NUM_PRODUCT_CARD INT NOT NULL,
    NUM_RANDOM_CARD BIGINT NOT NULL,
    EXP_DATE DATE NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    BALANCE BIGINT DEFAULT 0,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

-- Insertar 3 tarjetas en la tabla CARD
INSERT INTO CARD (CUSTOMER_ID, NUM_PRODUCT_CARD, NUM_RANDOM_CARD, EXP_DATE, STATUS, BALANCE) VALUES
(1, 12345, 6789012345678901, '2025-12-31', 'Active', 1000),
(1, 12346, 6789012345678902, '2024-11-30', 'Inactive', 500),
(2, 12347, 6789012345678903, '2026-10-15', 'Active', 1500);


-- Crear tabla TRANSACTION con relaciones a CARD y CUSTOMER
CREATE TABLE IF NOT EXISTS TRANSACTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CARD_ID BIGINT NOT NULL,
    PRICE BIGINT NOT NULL,
    EXP_DATE DATE NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    FOREIGN KEY (CARD_ID) REFERENCES CARD(ID)
);


-- Insertar 5 transacciones en la tabla TRANSACTION
INSERT INTO TRANSACTION (CARD_ID, PRICE, EXP_DATE, STATUS) VALUES
(1, 100,'2024-01-15', 'acepted'),
(1, 100,'2024-02-20', 'pending'),
(2, 100,'2024-03-10', 'annulled'),
(2, 100,'2024-04-05', 'annulled'),
(3, 100,'2024-05-25', 'acepted');
